version: "3.1"

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    env_file:
      - .env.production
    volumes:
      - /path/to/mongo/data:/data/db

  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    env_file:
      - .env.production

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
