version: "3.1"

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    env_file:
      - .env.production

  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
    env_file:
      - .env.production
